name: "Deploy Gig Tracker"

on:
  push:
    tags:
      - "gig-tracker/v*"

env:
    PROJECT_PATH: GigTracker/GigTracker.csproj

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish the project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained
