name: "Deploy Gig Tracker"

on:
  push:
    tags:
      - "gig-tracker/v*"

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files
        run: ls -R

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore GigTracker.csproj

      - name: Build the project
        run: dotnet build GigTracker.csproj -c Release --no-restore

      - name: Publish the project
        run: dotnet publish GigTracker.csproj -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: bin/Release/net6.0-windows/win-x64/publish/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
